"""oem104-create-fsbi-role

Revision ID: 30b3038752f1
Revises: 5ab66dd07312
Create Date: 2020-02-20 08:23:17.636246

"""
from alembic import op
from psycopg2.extensions import AsIs
from sqlalchemy.sql import text

import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION')
STAGE = os.environ.get('STAGE')
BI_SECRET = f'fwan-status/{STAGE}/fsbi'

# revision identifiers, used by Alembic.
revision = '30b3038752f1'
down_revision = '5ab66dd07312'
branch_labels = None
depends_on = None


def upgrade():
    from finitestate.common.aws.secrets import get_secret

    # ### commands generated by Alembic ###

    ###########################
    # Business Intelligence READ-ONLY user
    ###########################
    bi_secret = get_secret(BI_SECRET, AWS_DEFAULT_REGION)
    vals = {"username": AsIs(bi_secret['username']), "password": bi_secret['password']}
    op.get_bind().execute(
        text('''
        CREATE ROLE :username WITH LOGIN PASSWORD :password;
        GRANT SELECT ON process_status_detail, error_detail TO :username;
    '''), **vals)
    # ### end Alembic commands ###


def downgrade():
    from finitestate.common.aws.secrets import get_secret

    # ### commands generated by Alembic ###
    bi_secret = get_secret(BI_SECRET, AWS_DEFAULT_REGION)
    vals = {"username": AsIs(bi_secret['username'])}
    op.get_bind().execute(
        text('''
        REVOKE ALL ON error_detail, process_status_detail FROM :username;
        DROP ROLE :username;
    '''), **vals)
    # ### end Alembic commands ###
