"""OEM130 Create Analysis Status Tables

Revision ID: 95bfc564a7e7
Revises: 30b3038752f1
Create Date: 2020-02-20 09:20:55.319135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95bfc564a7e7'
down_revision = '30b3038752f1'
branch_labels = None
depends_on = None

activestage = sa.Enum('ANALYSIS', name='activestage')


def upgrade():
    # ### commands generated by Alembic ###
    op.create_table('active_component',
    sa.Column('fwan_process_id', postgresql.UUID(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('component_id', sa.Text(), nullable=False),
    sa.Column('active_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fwan_process_id', 'file_id', 'component_id')
    )
    op.create_index('active_component_start_idx', 'active_component', ['active_start_date'], unique=False)
    op.create_table('expired_component',
    sa.Column('fwan_process_id', postgresql.UUID(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('component_id', sa.Text(), nullable=False),
    sa.Column('expired_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fwan_process_id', 'file_id', 'component_id')
    )
    op.create_index('expired_component_idx', 'expired_component', ['expired_date'], unique=False)
    op.create_table('active_process',
    sa.Column('fwan_process_id', postgresql.UUID(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('active_stage', activestage, nullable=False),
    sa.Column('active_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fwan_process_id', 'file_id')
    )
    op.create_index('active_process_start_idx', 'active_process', ['active_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands generated by Alembic ###
    op.drop_index('active_process_start_idx', table_name='active_process')
    op.drop_table('active_process')
    op.drop_index('expired_component_idx', table_name='expired_component')
    op.drop_table('expired_component')
    op.drop_index('active_component_start_idx', table_name='active_component')
    op.drop_table('active_component')
    activestage.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
