import pyspark.sql.types
    
bin_info_info_schema = pyspark.sql.types.StructType([
    pyspark.sql.types.StructField('arch', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('baddr', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('binsz', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('bintype', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('bits', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('canary', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('class', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('compiled', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('compiler', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('crypto', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('dbg_file', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('endian', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('havecode', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('guid', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('intrp', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('laddr', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('lang', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('linenum', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('lsyms', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('machine', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('maxopsz', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('minopsz', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('nx', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('os', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('pcalign', pyspark.sql.types.LongType()),
    pyspark.sql.types.StructField('pic', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('relocs', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('relro', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('rpath', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('sanitiz', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('static', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('stripped', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('subsys', pyspark.sql.types.StringType()),
    pyspark.sql.types.StructField('va', pyspark.sql.types.BooleanType()),
    pyspark.sql.types.StructField('file_hash', pyspark.sql.types.StringType()),
])

