"""
firmware_unpacked_message.py

Class definitions for Firmware-based event notifications originally generated by
the Unpacker.
"""
import json
from uuid import UUID

from .base import FSPluginMessageBase


class FSFirmwareUnpackedMessage(FSPluginMessageBase):
    """Class for all Firmware unpacked event messages from firmware unpacker, serializable as JSON string.

    Args:
        firmware_id: SHA256 hash of source firmware to process.
        fwan_process_id: Used for all related status tracking events. Defaults to uuid4().
        trigger_downstream_plugins: If set to False does not send a message to trigger
            normal downstream events. Defaults to True.
    """
    def __init__(self, firmware_id: str, fwan_process_id: UUID, trigger_downstream_plugins: bool = True):
        super().__init__(fwan_process_id, trigger_downstream_plugins)
        self.firmware_id = firmware_id

    @property
    def storage_id(self) -> str:
        return self.firmware_id

    @property
    def status_id(self) -> str:
        return self.firmware_id

    @staticmethod
    def deserialize(json_string: str):
        return FSFirmwareUnpackedMessage(**json.loads(json_string))
